= Asciidoctor Documentation Site
// Settings:
:hide-uri-scheme:
ifdef::env-github[:badges:]
// Project URIs:
:uri-project: https://asciidoctor.org
//:uri-site: https://docs.asciidoctor.org
:uri-site: https://asciidoctor-docs.netlify.com
:uri-org: https://github.com/asciidoctor
:uri-site-ui: https://github.com/asciidoctor/docs.asciidoctor.org-ui
// External URIs:
:uri-antora-install: https://docs.antora.org/antora/1.1/install/install-antora/
:uri-letsencrypt: https://letsencrypt.org
:uri-netlify: https://www.netlify.com
:uri-netlify-deploys: https://app.netlify.com/sites/asciidoctor-docs/deploys

ifdef::badges[]
image:https://img.shields.io/travis/asciidoctor/docs.asciidoctor.org/master.svg[CI status,88,20,link=https://travis-ci.org/asciidoctor/docs.asciidoctor.org]
image:https://www.netlify.com/img/global/badges/netlify-dark.svg[Deploy Status,45,20,link={uri-netlify-deploys}]
endif::[]

This repository contains the playbook project for the Asciidoctor documentation site published at {uri-site}.

== Documentation Structure

The documentation components are pulled from various source repositories in the https://github.com/asciidoctor[Asciidoctor organization on GitHub].
The UI for the site is hosted in a separate repository, docs.asciidoctor.org-ui.

== Quickstart

To generate the Asciidoctor Docs site, you first need to {uri-antora-install}[install Antora].
Once Antora is installed, run the `antora` command on the playbook file hosted in this repository.

 $ antora antora-playbook.yml

The site will be generated into [.path]_public/_.
Navigate to [.path]_public/index.html_ in your browser to view the site offline.

== Hosting

This site is hosted on {uri-netlify}[Netlify].
It's managed by the account info [at] this domain.

Deployment is triggered via a webhook to any branch in the git repository (URL: https://api.netlify.com/hooks/gitlab, events: Push Events, Merge Requests Events).

The deploy job on Netlify is configured by the file [.path]_netlify.toml_.
This configuration files defines certain environment variables that control the behavior of Yarn and Antora.
When the job runs, it switches to the [.path]_netlify/_ directory, runs `yarn`, then invokes `antora`.

The Netlify deploy logs for docs.asciidoctor.org can be viewed at {uri-netlify-deploys}.

The site is also built nightly on Travis CI to pick up any updates to the content made during the day.
The nightly CI job, configured in [.path]_.travis.yml_, triggers the Netlify job by pinging the $NETLIFY_BUILD_HOOK url.

== Domain Name

The domain name for this site is configured using the following A record:

 docs 3600 IN A 104.198.14.52

The certificate for this site was generated by {uri-letsencrypt}[Let's Encrypt] and is shared with the certificate for asciidoctor.org.
See the https://asciidoctor.og#dns[asciidoctor.org README] for details about how it was generated and configured.

== TLS Certificate (https)

The TLS certificate for docs.asciidoctor.org was issued by {uri-netlify}[Netlify] using {uri-letsencrypt}[Let's Encrypt] and is automatically renewed.

Verify the certificate is valid using:

 $ curl -vI https://docs.asciidoctor.org

Look for `CN=docs.asciidoctor.org` under the "`Server certificate`" section.

Netlify redirects all traffic to HTTPS automatically (i.e., it forces HTTPS).

== Copyright and License

Copyright (C) 2012-2018 Dan Allen, Sarah White and the individual contributors to Asciidoctor.
Use of this software is granted under the terms of the MIT License.
