name: Retry Deploy Preview
on:
  issue_comment:
    types: [created]
jobs:
  pr-comment:
    if: |
      github.repository_owner == 'asciidoctor' && github.event.issue.pull_request &&
      github.event.issue.user.id == github.event.comment.user.id && github.event.comment.body == '/retry'
    runs-on: ubuntu-latest
    steps:
    - name: Retry Deploy Preview
      # see https://github.com/mojavelinux/retry-netlify-deploy-preview-action
      uses: mojavelinux/retry-netlify-deploy-preview-action@v1
      with:
        netlify-token: ${{ secrets.NETLIFY_TOKEN }}
        pull-request-url: ${{ github.event.issue.pull_request.url }} 
        site-name: asciidoctor-docs
